{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-identity.serviceAccountName" . }}
  labels:
    {{- include "agent-identity.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
